### PR TITLE
docs: add Egg.js showcase

### PR DESCRIPTION
**Pull request by atian25**
Egg.js is an framework for building better enterprise frameworks and apps with Node.js.

It's  opensource by Alibaba, and widely used at China.

### CODE REVIEW

**Comment by zhixiaoqiang** [comment]
only `yarn start` can usual run

**Comment by zhixiaoqiang** [comment]
only the `yarn start` command can run normally

**Comment by atian25** [comment]
> only the `yarn start` command can run normally

others scripts is removed.

I test with `npm start` is work fine.

**Comment by EricSimons** [comment]
This is awesome! Two small things that would make this perfect:

1. Can you save the package-lock.json file that is generated from install? This ensures subsequent visits are super fast for installation.
2. Can you include a `.stackblitzrc` file in the root that specifies the start command? for ex:

```
{
  "installDependencies": true,
  "startCommand": "npm start"
}
```

**Comment by atian25** [comment]
@EricSimons  sure, done.

**Review by EricSimons — APPROVED** [review]

**Comment by EricSimons** [comment]
Thanks! Amazing job on this 🙏

**Comment by xiaoxudoo** [comment]
It seems hot reload crashed for me：https://stackblitz.com/edit/webcontainer-egg-7pzrg4?file=app%2Fcontroller%2Fhome.js

**Pull request merged**
